config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "podcasts#index"
  root "podcasts#user_specific"

  resources :podcasts, only: [:index, :show] do
    collection do
      get 'user_specific'
      get 'explore'
      get 'library'
    end
    resources :likes, only: [:create, :destroy]
  end
  
  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id                    :bigint           not null, primary key
#  name                  :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  listen_notes_genre_id :integer
#
class Genre < ApplicationRecord
  has_many :user_genres, dependent: :destroy
  has_many :users, through: :user_genres
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  podcast_id :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_likes_on_podcast_id  (podcast_id)
#  index_likes_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (podcast_id => podcasts.id)
#  fk_rails_...  (user_id => users.id)
#
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :podcast, counter_cache: true
end

app/models/podcast.rb
# == Schema Information
#
# Table name: podcasts
#
#  id                      :bigint           not null, primary key
#  audio_url               :string
#  description             :text
#  duration                :integer
#  genres                  :integer          default([]), is an Array
#  host                    :string
#  likes_count             :integer          default(0)
#  thumbnail_url           :string
#  title                   :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  listen_notes_podcast_id :string
#
class Podcast < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
    
  validates_presence_of :title, :description, :duration, :audio_url, :host, :thumbnail_url
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                       :bigint           not null, primary key
#  email                    :string           default(""), not null
#  encrypted_password       :string           default(""), not null
#  first_name               :string
#  language                 :string
#  last_name                :string
#  preferred_podcast_length :integer
#  remember_created_at      :datetime
#  reset_password_sent_at   :datetime
#  reset_password_token     :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :user_genres, dependent: :destroy
  has_many :genres, through: :user_genres

  has_many :likes, dependent: :destroy
  has_many :liked_podcasts, through: :likes, source: :podcast

  # Validations
  validates_presence_of :first_name, :last_name, length: { maximum: 50 }
end

app/models/user_genre.rb
# == Schema Information
#
# Table name: user_genres
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  genre_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_user_genres_on_genre_id  (genre_id)
#  index_user_genres_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (genre_id => genres.id)
#  fk_rails_...  (user_id => users.id)
#
class UserGenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_podcast, only: [:create, :destroy]
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @podcast.likes.create(user_id: current_user.id)
    end
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
  end

  private

  def find_podcast
    @podcast = Podcast.find(params[:podcast_id])
  end

  def find_like
    @like = @podcast.likes.find(params[:id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, podcast_id: params[:podcast_id]).exists?
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index;end

  def user_specific
    # logic to load genre-related podcasts
    listen_notes_genre_ids = current_user.genres.pluck(:listen_notes_genre_id)
    @genre_related_podcasts = Podcast.where('genres && ARRAY[?]::integer[]', listen_notes_genre_ids).includes(:likes).all

    # render partial: 'user_specific_podcasts'
    render 'user_specific_podcasts'

  end
  
  def explore
    # logic to load all podcasts
    @podcasts = Podcast.includes(:likes).all

    # render partial: 'explore_podcasts'
    render 'explore_podcasts'

  end
  
  def library
    # logic to load user preferences
    # render partial: 'library_podcasts'
    render 'library_podcasts'
  end

  def show
    @podcast = Podcast.find(params[:id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :profile_params, only: [:update]
    before_action :set_user, only: [:show, :edit, :update]
 
    def show
    #  @favorites_podcasts = @user.favorite_podcasts
    #  @listening_histories = @user.listening_histories
    #  @user_recommendations = @user.user_recommendations
    end
 
    def edit
    end
 
    def update
      ActiveRecord::Base.transaction do
        @user.update!(profile_params)
        update_user_genres
        redirect_to profile_path, notice: 'Profile was successfully updated.'
      rescue ActiveRecord::RecordInvalid => e
        flash.now[:alert] = "Update failed: #{e.message}"
        render :edit, status: :unprocessable_entity
      rescue => e # Catch other unexpected exceptions
        flash.now[:alert] = "An unexpected error occurred: #{e.message}"
        render :edit, status: :internal_server_error
      end
    end
 
    private
 
    def set_user
     @user = current_user
    end
 
    def profile_params
     params.require(:user).permit(:preferred_podcast_length, :language, genre_ids: [])
    end

    def update_user_genres
      @user.user_genres.destroy_all
      genre_ids = params[:user][:genre_ids] || []
      genre_ids.each do |genre_id|
        @user.user_genres.create!(genre_id: genre_id)
      end
    end
 end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
  def already_liked?(podcast)
    Like.where(user_id: current_user.id, podcast_id: podcast.id).exists?
  end

  def find_like(podcast)
    Like.find_by(user_id: current_user.id, podcast_id: podcast.id)
  end

  def genres_name(podcast)
    Genre.where(listen_notes_genre_id: podcast.genres).pluck(:name).join(', ')
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_header.html.erb
<!-- Header -->
<nav class="navbar fixed-top navbar-light bg-light">
  <div class="container-fluid">
    <ul class="nav nav-justified w-100">
      <li class="nav-item">
        <h2>Supercast</h2>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar fixed-bottom navbar-light bg-light">
  <div class="container-fluid">
    <ul class="nav nav-justified w-100">
      <li class="nav-item">
        <a class="nav-link" data-turbo-frame="podcast-content" href="<%= user_specific_podcasts_path %>">
          <i class="bi bi-house-door-fill"></i>
          Home
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-turbo-frame="podcast-content" href="<%= explore_podcasts_path %>">
          <i class="bi bi-search"></i>
          Explore
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-turbo-frame="podcast-content" href="<%= library_podcasts_path %>">
          <i class="bi bi-collection-play-fill"></i>
          Library
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supercast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <%= yield %>
    <% if user_signed_in? %> 
      <%= render 'layouts/navbar' %>
    <% end %>
  </body>
</html>

app/views/podcasts/explore_podcasts.html.erb
<h3>Explore</h3>
<% if @podcasts %>
  <div class="list-group text-center">
    <% @podcasts.each do |podcast| %>
      <div class="list-group-item p-3">
        <h5><%= link_to podcast.title, podcast_path(podcast), class: "mb-1 text-decoration-none" %></h5>

        <p class="mb-1">Genre: <%= genres_name(podcast) %></p>
        <%= image_tag podcast.thumbnail_url, alt: podcast.title, class: "img-fluid rounded" %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>There are no podcasts to explore.</p>
<% end %>

app/views/podcasts/index.html.erb
<% if user_signed_in? %> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <%= link_to 'My Profile', profile_path %>
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<h5>Hello, <%= current_user.first_name %></h5>

app/views/podcasts/library_podcasts.html.erb
<div class="container">
  <div class="row mb-3">
    <h3>Library</h3>
  </div>

  <div class="row">
    <h5>Listening History</h5>
    <p>Coming soon!</p>
  </div>
  <div class="row">
    <h5>Queue</h5>
    <p>Coming soon!</p>
  </div>
</div>


<!-- this would be moved into the header section later on -->
<% if user_signed_in? %> 
  <%= link_to 'My Profile', profile_path %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

app/views/podcasts/show.html.erb
<div class="container p-0 m-0 mb-5">
  <div class="podcast-item mb-3 border-bottom p-3">
    <div class="row">
      <div class="col-3">
        <%= image_tag @podcast.thumbnail_url, alt: @podcast.title, class: "img-fluid rounded-start" %>
      </div>
      <div class="col-5 pt-3">
        <h6 class="p-0 m-0"><%= @podcast.host %></h6>
        <%= time_ago_in_words(@podcast.created_at) %> ago
      </div>
    </div>
    <div class="row p-3">
      Genre: <%= genres_name(@podcast) %>
    </div>

    <div class="row p-3">
      <div class="col-12">
        <%= audio_tag @podcast.audio_url, controls: true %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-12">
        <h5><%= @podcast.title %></h5>
        <p><%= @podcast.description %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-4 p-2 border border-2 rounded-3">
        <i class="bi bi-play-circle"></i>
        <%= (@podcast.duration / 60).to_i %> mins
      </div>
      <div class="col-4 p-2">
        <% if already_liked?(@podcast) %>
          <i class="bi bi-heart"></i>
          Unlike <%= @podcast.likes_count %>
        <% else %>
          <i class="bi bi-heart"></i>
          Like <%= @podcast.likes_count %>
        <% end %>
      </div>
      <div class="col-4 p-2">
        <i class="bi bi-plus-square"></i>
        Queue
      </div>
    </div>
  </div>
</div>

app/views/podcasts/user_specific_podcasts.html.erb
<div class="container p-0 m-0">
  <h3>For you</h3>
  <% if @genre_related_podcasts.present? %>
    <div class="podcasts-container">
      <% @genre_related_podcasts.each do |podcast| %>
        <!-- Example structure for a podcast card, repeat for each podcast -->
        <div class="podcast-item mb-3 border-bottom p-3">
          <div class="row">
            <div class="col-3">
              <%= image_tag podcast.thumbnail_url, alt: podcast.title, class: "img-fluid rounded-start" %>
            </div>
            <div class="col-5 pt-3">
              <h6 class="p-0 m-0"><%= truncate(podcast.host, length: 15) %></h6>
              <%= time_ago_in_words(podcast.created_at) %> ago
            </div>
          </div>

          <div class="row mt-2">
            <div class="col-12">
              <h5><%= link_to podcast.title, podcast_path(podcast), class: "text-decoration-none" %></h5>
              <p><%= truncate(podcast.description, length: 100) %></p>
            </div>
          </div>

          <div class="row">
            <div class="col-4 p-2 border border-2 rounded-3">
              <i class="bi bi-play-circle"></i>
              <%= (podcast.duration / 60).to_i %> mins
            </div>
            <div class="col-4 p-2">
              <% if already_liked?(podcast) %>
                <i class="bi bi-heart"></i>
                Unlike <%= podcast.likes_count %>
              <% else %>
                <i class="bi bi-heart"></i>
                Like <%= podcast.likes_count %>
              <% end %>
            </div>
            <div class="col-4 p-2">
              <i class="bi bi-plus-square"></i>
              Queue
            </div>
          </div>


        </div>
      <% end %>
    </div>
  <% else %>
    <p>There are no podcasts for you yet, please update your preferences!</p>
    <%= link_to 'My Profile', profile_path %>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<%= turbo_frame_tag "modal" do %>

<h2>Edit Profile</h2>

<%= form_for @user, url: profile_path, method: :patch do |f| %>
  <div class="field">
    <%= f.label :favorite_genres %><br />
    <% Genre.all.each do |genre| %>
        <%= check_box_tag 'user[genre_ids][]', genre.id, @user.genres.include?(genre) %>
        <%= label_tag genre.name %><br />
    <% end %>
  </div>

  <div class="field">
    <%= f.label :preferred_podcast_length %><br />
    <%= f.number_field :preferred_podcast_length, placeholder: 'In minutes' %>
  </div>

  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language, value: 'English', readonly: true %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Profile' %>
  </div>
<% end %>
    
<% end %>

app/views/profiles/show.html.erb
<h2><%= @user.first_name %>'s Profile</h2>
<p><strong>Favorite Genres:</strong> 
    <% @user.genres.each do |genre| %>
        <%= genre.name %>
    <% end %>
</p>

<p><strong>Preferred Podcast Length:</strong> <%= @user.preferred_podcast_length %> mins</p>
<p><strong>Language:</strong> <%= @user.language %></p>


<h3>Favorite Podcasts</h3>

<h3>Listening History</h3>

<h3>Recommended Podcasts</h3>

<%= link_to 'Edit Profile', edit_profile_path, data: { turbo_frame: "modal" } %>